.class public Lanta/ㆴ/ぺ;
.super Ljava/lang/Object;
.source "AppConst.java"


# static fields
.field public static 㕇:Ljava/lang/String; = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaXRlX2NvZGUiOiJkb3Vkb3UiLCJ1aWQiOiI1NDVmNzA3ZTU3NTU0YTliYjEyM2VmMjdjMTM5NzY1YSIsInVzZXJuYW1lIjoiZ3Vlc3Q4NzAzIiwidXNlcl90eXBlIjoiZ3Vlc3QiLCJsaW5lX2NvZGUiOiJkZWZhdWx0Iiwic2Vzc2lvbl9pZCI6IjQyMTU0YTA3NTFkZjQxNDBhNWQzOWNkNWFjOTg5YzE5IiwiaXNfbW9iaWxlIjpmYWxzZSwiaWF0IjoxNjYyMTA4NDQzfQ.dFA4OOHVFgHBqpVkhclIQltDv2WIZ6VYJLjoR-ULbM8"
