# Generated by Django 4.2.14 on 2024-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkAllUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=255)),
                ('urls', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlackURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EigenValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=255)),
                ('api_calls', models.IntegerField()),
                ('permissions', models.IntegerField()),
                ('suspicious_resources', models.IntegerField()),
                ('entropy', models.FloatField()),
                ('version', models.CharField(max_length=50)),
                ('storage', models.FloatField()),
                ('base_name_length', models.IntegerField()),
                ('top_level_domain_match', models.BooleanField()),
                ('sensitive_api_count', models.IntegerField()),
                ('md5_value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=255)),
                ('Owner', models.CharField(max_length=255, verbose_name='Owner')),
                ('issuer', models.CharField(max_length=255, verbose_name='Issuer')),
                ('serialNumber', models.CharField(max_length=255, verbose_name='Serial Number')),
                ('validData', models.CharField(max_length=255, verbose_name='Valid Data')),
                ('Sha256FingerPrint', models.CharField(max_length=255, verbose_name='SHA-256 Fingerprint')),
            ],
        ),
        migrations.CreateModel(
            name='MessageAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=255)),
                ('CN', models.CharField(max_length=255, verbose_name='Common Name')),
                ('OU', models.CharField(max_length=255, verbose_name='Organizational Unit')),
                ('O', models.CharField(max_length=255, verbose_name='Organization')),
                ('L', models.CharField(max_length=255, verbose_name='Locality')),
                ('ST', models.CharField(max_length=255, verbose_name='State/Province')),
                ('C', models.CharField(max_length=255, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=255)),
                ('predicted_result', models.CharField(max_length=50)),
                ('black_prob', models.FloatField()),
                ('gamble_prob', models.FloatField()),
                ('scam_prob', models.FloatField()),
                ('sex_prob', models.FloatField()),
                ('white_prob', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=255)),
                ('white', models.IntegerField(verbose_name='White List Count')),
                ('whiteUnMatched', models.IntegerField(verbose_name='WhiteUn List Count')),
                ('black', models.IntegerField(verbose_name='Black List Count')),
                ('BlackUnMatched', models.IntegerField(verbose_name='WhiteUn List Count')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
