# Generated by Django 4.1 on 2024-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EigenValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=255)),
                ('api_calls', models.IntegerField()),
                ('permissions', models.IntegerField()),
                ('suspicious_resources', models.IntegerField()),
                ('entropy', models.FloatField()),
                ('version', models.CharField(max_length=50)),
                ('storage', models.FloatField()),
                ('base_name_length', models.IntegerField()),
                ('top_level_domain_match', models.BooleanField()),
                ('sensitive_api_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=255)),
                ('predicted_result', models.CharField(max_length=50)),
                ('black_prob', models.FloatField()),
                ('gamble_prob', models.FloatField()),
                ('scam_prob', models.FloatField()),
                ('sex_prob', models.FloatField()),
                ('white_prob', models.FloatField()),
            ],
        ),
    ]
